/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['sum.js']) {
  _$jscoverage['sum.js'] = [];
  _$jscoverage['sum.js'][2] = 0;
  _$jscoverage['sum.js'][3] = 0;
}
_$jscoverage['sum.js'][2]++;
module.exports = (function (a, b) {
  _$jscoverage['sum.js'][3]++;
  return a + b;
});
_$jscoverage['sum.js'].source = ["// test","module.exports = function(a, b) {","  return a + b;","}"];
